config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label< ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings

  scope :search_label, -> (label_id) { find_by(id: label_id).tasks }
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  scope :search_title, -> (title){ where('title like ?',"%#{title}%") }
  scope :search_status, -> (status){ where(status: status) }
  scope :search_priority, -> (priority){ where(priority: priority) }

  enum priority: { 高: 2, 中: 1, 低: 0 }

  belongs_to :user

  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }

  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  validates :email, uniqueness: true

  has_many :tasks, dependent: :destroy

  before_update :admin_cannot_update
  before_destroy :admin_cannot_delete

  private

  def admin_cannot_update
    throw :abort if User.exists?(admin: true) && self.admin_change_to_be_saved == [true, false]
  end

  def admin_cannot_delete
    throw :abort if User.exists?(admin: true) && self.admin
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :check_admin

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # 保存の成功した場合の処理
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def index
    @users = User.includes(:tasks)
  end

  def show
    @user = User.find(params[:id])
    # ユーザのタスク一覧
    @tasks = Task.where(user_id: @user.id)
  end
      # 編集画面
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path, notice: "更新しました。"
    else
      render "edit"
    end
  end
  # 削除
  def destroy
    user= User.find(params[:id])

    user.destroy
    redirect_to admin_users_path, notice: "削除しました。"
  end



  private

  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation, :admin)
  end

  def check_admin
    if current_user.admin? == false
      redirect_to tasks_path, notice: "管理者以外はアクセスできない！"
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  def top
    @tasks = Tasl.page(params[:page]).per(6).order('updated_at DESC')
  end

  private

  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  # GET /labels or /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to label_url(@label), notice: "Label was successfully created." }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to label_url(@label), notice: "Label was successfully updated." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # 一覧画面
  def index
    @tasks = current_user.tasks.order(created_at: :desc)

    if params[:sort_expired] == "true"
      @tasks = @tasks.all.order(enddate: :desc)
    end

    if params[:sort_priority] == "true"
      @tasks = @tasks.all.order(priority: :desc)
    end

    if params[:task]&&params[:task][:title].present?
      @tasks = @tasks.search_title(params[:task][:title])
    end

    if params[:task]&&params[:task][:priority].present?
      @tasks = @tasks.search_priority(params[:task][:priority])
    end

    if params[:task]&&params[:task][:status].present?
      @tasks = @tasks.search_status(params[:task][:status])
    end

    if params[:task] && params[:task][:label_id].present?
      @tasks = Label.search_label(params[:task][:label_id])
    end


    @tasks = @tasks.page(params[:page]).per(5)


  end

  # 詳細画面
  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to task_url(@task), notice: "登録しました。"
    else
      render "new"
    end
  end

  # 編集画面
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to task_url(@task), notice: "更新しました。"
    else
      render "edit"
    end
  end

  # 削除
  def destroy
    task = Task.find(params[:id])

    task.destroy
    redirect_to tasks_url, notice: "削除しました。"
  end

  def confirm
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end

  private

  # Strong Parameters
  def task_params
    params.require(:task).permit(:title, :content, :enddate, :status, :priority, { label_ids: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    if current_user
      redirect_to tasks_path
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # 保存の成功した場合の処理
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to tasks_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)

  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true, url: admin_user_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <div class="field">
    <%= f.label :管理者 %>
    <%= f.check_box :admin, id: :admin_check,:as => :boolean%>
  </div>

  <%= f.submit "Create my account" %>

<% end %>

app/views/admin/users/index.html.erb
<h2>ユーザー一覧</h2>

<% @users.each do |user| %>
  <li>
    <td><%= link_to '詳細を確認する', admin_user_path(user.id) %></td>
    <span class="user-name"><%= user.name %></span>
    <span class="user-email"><%= user.email %></span>
    <span class="user-email"><%= user.tasks.size %></span>
    <%= link_to "編集", edit_admin_user_path(user), class: "btn btn-success" %>
    <%= link_to "削除", admin_user_path(user), method: :delete, class: "btn btn-danger" %>
  </li>
<% end %>
<%= link_to "ユーザー作成", new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ(管理画面)</h1>

<p>メールアドレス: <%= @user.email %></p>

# タスク一覧表示
<% @tasks.each do |task| %>
  <li>
    <span class="task-title"><%= task.title %></span>
    <span class="task-enddate"><%= task.enddate %></span>
    <span class="task-status"><%= task.status %></span>
    <span class="task-priority"><%= task.priority %></span>
    <%= link_to "詳細", task, class: "btn btn-info" %>
    <%= link_to "編集", edit_task_path(task), class: "btn btn-success" %>
    <%= link_to "削除", task, method: :delete, class: "btn btn-danger" %>
  </li>
<% end %>

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


     <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
     <% end %>

     <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
     <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
     <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if task.errors.present? %>
  <ul>
    <% task.errors.full_messages.each do |message| %>
      <li><%= message %>
    <% end %>
  </ul>
<% end %>
<%= form_with model: task do |form| %>
  <div>
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, "内容" %>
    <%= form.text_field :content %>
  </div>
  <div>
  <%= form.label :priority, "優先順位" %>
  <%= form.select :priority, Task.priorities.keys, class:"form-control" %>
</div>
  <div>
    <%= form.label :status, "ステータス" %>
    <%= form.select :status, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]] ,class:"form-control" %>
  </div>
    <%= form.label :content, "終了期限" %>
    <%= form.date_field :enddate %>
  </div>

  <div class="field">
  <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>
  <div>
    <%= form.submit "保存" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>タスク編集</h2>

<%= render partial: "form", locals: { task: @task } %>

<%= link_to "一覧へ", tasks_path %>

app/views/tasks/index.html.erb
<h2>タスク一覧</h2>


<table>
<%= form_with scope: :task, method: :get, url: tasks_path do |form| %>
  <div>
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>

  </div>
  <div>
    <%= form.label :status, "ステータス" %>
    <%= form.select :status, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]], { include_blank: '選択してください'}, {class:"form-control"} %>
  </div>
  <div>
    <%= form.label :priority, "優先順位" %>
    <%= form.select :priority, [["高", "高"], ["中", "中"], ["低", "低"]], { include_blank: '選択してください'}, {class:"form-control"} %>
  </div>

  <%= form.select(:label_id, Label.pluck(:name, :id), { include_blank: true }) %>
  <%= form.submit "送信" %>
<% end %>

<% @tasks.each do |task| %>
  <li>
  <span class="task-name"><%= task.user.name %></span>
    <span class="task-title"><%= task.title %></span>
    <span class="task-enddate"><%= task.enddate %></span>
    <span class="task-status"><%= task.status %></span>
    <span class="task-priority"><%= task.priority %></span>

    <% task.labels.each do |label| %>
      <%= label.name %>
    <% end %>

    <%= link_to "詳細", task, class: "btn btn-info" %>
    <%= link_to "編集", edit_task_path(task), class: "btn btn-success" %>
    <%= link_to "削除", task, method: :delete, class: "btn btn-danger" %>
  </li>
<% end %>



<%= link_to "新規登録", new_task_path %>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %>
<%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %>

<%= paginate @tasks %>

app/views/tasks/management.html.erb
<h1>Task#management</h1>
<p>Find me in app/views/task/management.html.erb</p>

app/views/tasks/new.html.erb
<h2>タスク新規登録</h2>

<%= render partial: "form", locals: { task: @task } %>

<%= link_to "一覧へ", tasks_path %>

app/views/tasks/show.html.erb
<h2>タスク詳細</h2>

<h3>タイトル</h3>

<p><%= @task.title %></p>

<h3>内容</h3>

<p><%= @task.content %></p>

<h3>ステータス</h3>

<p><%= @task.status %></p>

<h3>優先順位</h3>

<p><%= @task.priority %></p>

<h3>ラベル</h3>

<p><% @task.labels.each do |label| %></p>
<span class="task-name"><%= label.name %></span>
<% end %>

<h3>終了期限</h3>

<p><%= @task.enddate %></p>

<%= link_to "一覧へ", tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>